#!/usr/bin/env python3
"""Generate the README "Supported Resources" table from docs/resources/.

Reads every Markdown file under docs/resources/, extracts the
`subcategory` frontmatter value and the `description: |-` block, groups
resources by subcategory in a canonical order, sorts alphabetically
within each group, and emits a grouped Markdown listing.

Modes:
    (default)   write the table to stdout
    --write     replace the section between the AUTO-GENERATED markers
                in README.md in-place
    --check     fail with exit code 1 if README.md is out of sync with
                what the generator would produce (for CI)

The script is intentionally dependency-free (stdlib only) and
deterministic: same docs/resources/ contents always produce the same
output.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DOCS_DIR = REPO_ROOT / "docs" / "resources"
README = REPO_ROOT / "README.md"

START_MARKER = "<!-- AUTO-GENERATED RESOURCES START -->"
END_MARKER = "<!-- AUTO-GENERATED RESOURCES END -->"

# Canonical ordering of subcategories. Anything not listed here is
# appended at the end alphabetically (and warned about on stderr).
CANONICAL_ORDER = [
    "Base",
    "Authorization",
    "Identity",
    "Network",
    "Compute",
    "Container",
    "Web",
    "Storage",
    "Database",
    "Messaging",
    "Integration",
    "Key Vault",
    "Monitor",
    "Log Analytics",
    "Recovery",
]


def parse_doc(path: Path) -> tuple[str, str, str]:
    """Return (resource_name, subcategory, short_description) for one doc.

    `resource_name` is the file stem prefixed with `azuresim_`.
    """
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        raise ValueError(f"{path.name}: missing frontmatter")

    # Extract the frontmatter block.
    end = text.find("\n---", 3)
    if end == -1:
        raise ValueError(f"{path.name}: unterminated frontmatter")
    frontmatter = text[3:end]

    sub_match = re.search(r'^subcategory:\s*"?([^"\n]+?)"?\s*$', frontmatter, re.MULTILINE)
    if not sub_match:
        raise ValueError(f"{path.name}: missing subcategory")
    subcategory = sub_match.group(1).strip()

    # description: |-
    #   First line of description.
    desc_match = re.search(
        r'^description:\s*\|-?\s*\n((?:[ \t]+.*\n?)+)',
        frontmatter,
        re.MULTILINE,
    )
    if not desc_match:
        raise ValueError(f"{path.name}: missing description block")
    desc_lines = [line.strip() for line in desc_match.group(1).splitlines() if line.strip()]
    short_description = desc_lines[0] if desc_lines else ""

    resource_name = f"azuresim_{path.stem}"
    return resource_name, subcategory, short_description


def render_table(rows: list[tuple[str, str, str]]) -> str:
    """Render the grouped Markdown listing."""
    groups: dict[str, list[tuple[str, str]]] = {}
    for name, subcategory, description in rows:
        groups.setdefault(subcategory, []).append((name, description))

    ordered_keys: list[str] = []
    for key in CANONICAL_ORDER:
        if key in groups:
            ordered_keys.append(key)
    leftover = sorted(set(groups) - set(CANONICAL_ORDER))
    if leftover:
        print(
            f"warning: unrecognized subcategories appended at end: {leftover}",
            file=sys.stderr,
        )
        ordered_keys.extend(leftover)

    lines: list[str] = []
    lines.append(START_MARKER)
    lines.append("")
    lines.append(
        "> This section is auto-generated by `scripts/generate-resource-table.py` "
        "from the per-resource docs under `docs/resources/`. Run the script after "
        "adding a new resource doc; CI verifies it stays in sync."
    )
    lines.append("")
    total = sum(len(v) for v in groups.values())
    lines.append(
        f"{total} resource types across {len(ordered_keys)} subcategories. "
        f"Each row links to its per-resource doc."
    )
    lines.append("")
    for key in ordered_keys:
        lines.append(f"### {key}")
        lines.append("")
        lines.append("| Resource | Description |")
        lines.append("|---|---|")
        for name, description in sorted(groups[key]):
            stem = name[len("azuresim_"):]
            lines.append(f"| [`{name}`](docs/resources/{stem}.md) | {description} |")
        lines.append("")
    lines.append(END_MARKER)
    return "\n".join(lines)


def load_rows() -> list[tuple[str, str, str]]:
    if not DOCS_DIR.is_dir():
        raise SystemExit(f"docs directory not found: {DOCS_DIR}")
    docs = sorted(DOCS_DIR.glob("*.md"))
    if not docs:
        raise SystemExit(f"no resource docs under {DOCS_DIR}")
    return [parse_doc(p) for p in docs]


def replace_section(readme_text: str, new_block: str) -> str:
    pattern = re.compile(
        re.escape(START_MARKER) + r".*?" + re.escape(END_MARKER),
        re.DOTALL,
    )
    if not pattern.search(readme_text):
        raise SystemExit(
            "README.md is missing the AUTO-GENERATED markers; "
            "add them manually before running --write."
        )
    return pattern.sub(new_block, readme_text)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--write", action="store_true", help="rewrite README.md in place")
    group.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if README.md is out of sync with the generator",
    )
    args = parser.parse_args()

    rows = load_rows()
    new_block = render_table(rows)

    if args.write:
        text = README.read_text(encoding="utf-8")
        updated = replace_section(text, new_block)
        if updated != text:
            README.write_text(updated, encoding="utf-8")
            print(f"updated {README}", file=sys.stderr)
        else:
            print(f"{README} already up to date", file=sys.stderr)
        return 0

    if args.check:
        text = README.read_text(encoding="utf-8")
        match = re.search(
            re.escape(START_MARKER) + r".*?" + re.escape(END_MARKER),
            text,
            re.DOTALL,
        )
        if not match:
            print("README.md is missing the AUTO-GENERATED markers", file=sys.stderr)
            return 1
        if match.group(0) != new_block:
            print(
                "README.md resource section is out of sync. "
                "Run: python3 scripts/generate-resource-table.py --write",
                file=sys.stderr,
            )
            return 1
        return 0

    print(new_block)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
